stages:
  tokenize:
    cmd: cmake -B tokenizer/build -S tokenizer -DCMAKE_BUILD_TYPE=Release && cmake --build tokenizer/build -j10 && ./tokenizer/build/tokenize
    deps:
      - tokenizer/CMakeLists.txt
      - tokenizer/src/decode.cpp
      - tokenizer/src/lib/dataloader.cpp
      - tokenizer/src/lib/dataloader.hpp
      - tokenizer/src/lib/io.cpp
      - tokenizer/src/lib/io.hpp
      - tokenizer/src/lib/text.cpp
      - tokenizer/src/lib/text.hpp
      - tokenizer/src/lib/text_test.cpp
      - tokenizer/src/lib/threading.cpp
      - tokenizer/src/lib/threading.hpp
      - tokenizer/src/lib/tokenizer.cpp
      - tokenizer/src/lib/tokenizer.hpp
      - tokenizer/src/lib/tokenizer_test.cpp
      - tokenizer/src/tokenize.cpp
      - tokenizer/src/visualize.cpp
    outs:
      - out/tokenize

  train:
    cmd: uv run python src/train.py
    deps:
      - out/tokenize
      - src/train.py
      - src/models/model.py
      - src/dataloaders/data_loader.py
    params:
      - data
      - model
      - training
      - other
    outs:
      - out/train/checkpoints/best.pt
      - out/train/checkpoints/latest.pt
      - out/train/logs:
          persist: true
