stages:
  tokenize:
    cmd: mkdir -p tokenizer/build && cmake -S tokenizer -B tokenizer/build -DCMAKE_BUILD_TYPE=Release && cmake --build tokenizer/build -j$(nproc) && ./tokenizer/build/tokenize
    deps:
      - tokenizer/CMakeLists.txt
      - tokenizer/src/lib/dataloader.cpp
      - tokenizer/src/lib/dataloader.hpp
      - tokenizer/src/lib/io.cpp
      - tokenizer/src/lib/io.hpp
      - tokenizer/src/lib/text.cpp
      - tokenizer/src/lib/text.hpp
      - tokenizer/src/lib/threading.cpp
      - tokenizer/src/lib/threading.hpp
      - tokenizer/src/lib/tokenizer.cpp
      - tokenizer/src/lib/tokenizer.hpp
      - tokenizer/src/tokenize.cpp
    params:
      - tokenize
    outs:
      - out/tokenize

  train:
    cmd: uv run python src/train.py
    deps:
      - out/tokenize
      - src/train.py
      - src/models/qwen3.py
      - src/dataloaders/py150.py
      - src/dataloaders/py150_dataloader.py
      - src/trainers/trainer.py
    params:
      - tokenize.dataset_file
      - tokenize.tok_file
      - tokenize.vocab_size
      - data.seq_length
      - data.max_tokens
      - data.num_workers
      - data.bos_token_id
      - data.eos_token_id
      - data.pad_token_id
      - model
      - training
    outs:
      - out/train/checkpoints/best.ckpt
      - out/train/checkpoints/latest.ckpt
      - out/train/logs:
          persist: true
    metrics:
      - out/train/checkpoints/metrics.json:
          cache: false
