data:
  train_file: "out/tokenize/train.bin"
  val_file: "out/tokenize/val.bin"
  tok_file: "out/tokenize/tok.bin"
  train_paths_file: "out/tokenize/train_paths.txt"
  val_paths_file: "out/tokenize/val_paths.txt"
  dataset_path: "data/py150/data"
  glob_pattern: "*.py"
  split_ratio: 0.7
  seed: 42
  max_unique_words: 0
  vocab_size: 20259 # 256 byte tokens + 20000 BPE merges + 3 special tokens (EOS, PAD, UNK)
  pattern: ' ?[A-Za-z_(][A-Za-z_.]*|%(?:\.\d+)?[sdifFeEgGxXoc%]|[0-9]{1,3}| ?[^ %_A-Za-z0-9]+(?: ")?[\r\n]*|%|\s+$|\s+(?=\s)|\s'
  bos_token: ""
  eos_token: "<|endoftext|>"
  pad_token: "<|pad|>"
  seq_length: 256
  num_workers: 2
  eos_token_id: 20256 # <|endoftext|> token for document boundaries

model:
  # Qwen3 architecture parameters
  hidden_size: 512
  num_hidden_layers: 4
  num_attention_heads: 16
  num_key_value_heads: 8
  intermediate_size: 1024
  max_position_embeddings: 2048
  rope_theta: 10000.0
  attention_dropout: 0.1
  rms_norm_eps: 0.000001
  use_sliding_window: false
  sliding_window: 4096

training:
  prefix: "qwen3"
  batch_size: 32
  epochs: 50
  lr: 0.0001
  weight_decay: 0.01
  grad_clip: 1.0
  gradient_accumulation_steps: 4
  max_batches_per_epoch: 750 # Set to integer to limit batches per epoch, null for no limit
  use_amp: false # Use automatic mixed precision training
  compile_mode: "max-autotune" # Options: null, "default", "reduce-overhead", "max-autotune", "max-autotune-no-cudagraphs"
  seed: 42
  warmup_steps: 5 # Number of warmup steps for learning rate
  scheduler_t_max: 50 # T_max for CosineAnnealingLR (epochs)

other:
  save_dir: "out/train/checkpoints"
  log_dir: "out/train/logs"
