[project]
name = "llm-train"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.3",
    "peft>=0.17.1",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
]
